from .BaseAgent import *
from .VanillaDQN import *
from .DQN import *
from .DDQN import *
from .MaxminDQN import *
from .EnsembleDQN import *
from .OrderDQN import *
from .AdaOrderDQN import *
from .AdaAverageDQN import *
from .AdaMaxminDQN import  *
from .AveragedDQN import *
from .WDQN import *
from .SCDQN import *
from .SoftmaxDQN import *
from .EBDQN import *
from .REDQN import *
from .AdaEDQN import *